### ISSUE TITLE
Fix build race conditions in Jenkins

### ISSUE THREAD

**Issue by dkess** [0xcf/decal#4]
Notice builds 30 and 31 on Jenkins. These correspond to pushes that happened within a few seconds of each other. Build 30 started first, but finished after 31, causing the changes of build 31 to get overwritten and the website to display an old version. After noticing this, I manually ran a build to fix the problem-- but there should be a way to ensure this doesn't happen.

@jvperrin, any ideas?

**Comment by jvperrin** [comment]
It should be possible to make the builds just block each other so that this never happens: https://stackoverflow.com/a/43963315/1979001

**Comment by abizer** [comment]
this is a cool problem to have, decal goes industry

**Comment by abizer** [comment]
oops
